import { collection, Config, fields } from "@keystatic/core";
import { wrapper } from "@keystatic/core/content-components";

export const markdocConfig = fields.markdoc.createMarkdocConfig({});

export const keystaticConfig: Config = {
  storage: {
    kind: "local",
  },
  collections: {
    // Generated by keystatic nextjs starter
    posts: collection({
      label: "Posts",
      slugField: "title",
      path: "posts/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({ name: { label: "Title" } }),
        content: fields.markdoc({ label: "Content" }),
      },
    }),
    // New docs format
    docs: collection({
      label: "Docs",
      slugField: "title",
      path: "src/app/docs/*/page", // Create a 'page' file in this format, with '*' as slug string and as a folder
      format: {
        contentField: "content", // To output a single file based on schema.content.extension
      },
      schema: {
        title: fields.slug({ name: { label: "Title" } }),
        content: fields.markdoc({
          label: "Content",
          extension: "md", // defaults to .mdoc, but markdoc nextjs uses .md
          components: {
            button: wrapper({
              label: "Button",
              schema: {
                variant: fields.select({
                  label: "Variant",
                  defaultValue: "primary",
                  options: [
                    {
                      label: "Primary",
                      value: "primary",
                    },
                  ],
                }),
              },
            }),
          },
        }),
      },
    }),
  },
};
